name: Build docker image

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache
      uses: actions/cache@v3
      with: 
        path: ${{ github.workspace }}/cache
        key: docker-${{ runner.os }}-${{ hashfiles('cache/**') }}
        restore-keys: |
          docker-${{ runner.os }}-
    - name: Build Docker image
      run: >
        docker buildx build .
        --cache-from "type=local,src=$GITHUB_WORKSPACE/cache"
        --cache-to "type=local,dest=$GITHUB_WORKSPACE/cache"
        --tag ghcr.io/rijkvp/drainpipe:dev
        --push
